### PR TITLE
Add support for entities

### PR DESCRIPTION
**Pull request by domrout**
I've added models for Urls, hashtags, mentions and media in tweets (read only as far as I know). 

I edited enough configuration to make the gem build properly for me (I think README needed referencing as README.md?)

Also committed the gemspec itself, as this allows the gem to be compiled straight from the git repository using bundler.

### CODE REVIEW

**Comment by mbbx6spp** [comment]
@domrout This looks fantastic. Thanks so much.

Would it be possible for you to make just a three minor tweaks and push the new commits to this same branch?
- Remove the gem spec file; this should be generated.
- Change the target branch to submit the pull request to, to twitter4r-core/v0.8.0
- Remove the "/1" and "api.twitter.com" changes from the configuration file (because I already added that to v0.8.0 branch over the weekend and I wanted to track those changes in separate commits in the main repository log - the pull request will be just one commit eventually).

The reason of the change in branch target for this pull request is that there do not appear to be any tests for the Entities and I wanted to add those before merging to master as I was hoping to keep master "stable", i.e. stuff with tests even if they aren't terribly risky changes.

If you resubmit then I can keep a clean history with your attribution in Git ;)

Wonderful stuff and should make it into the v0.8.0 release scheduled for Friday afternoon/evening (US time).

**Comment by mbbx6spp** [comment]
Sorry give me 5 minutes to push the v0.8.0 up to the GH remote. Sorry, my bad.

**Comment by mbbx6spp** [comment]
Actually ignore my crazy ramblings before. I am pulling this in my local git repo from your public GH fork of twitter4r-core and attributing your information to the compacted/cleanly merged commit. I will post the GH link to the new commit after I push and then close this pull request.

**Comment by domrout** [comment]
It looks like you were good to your word so I'll close the pull request.

I may try adding some tests to my repo if I get a moment of downtime before Friday. I feel bad for suggesting code without writing any spectests, but deadlines abound and I'm not very sure how to approach it.

**Comment by mbbx6spp** [comment]
Do not worry. I appreciate any useful code submissions like this! Thanks :)

**Pull request closed without merging**
